### ISSUE TITLE
Check cross-concept cognates

### ISSUE THREAD

**Issue by chrzyki** [lexibank/bowernpny#11]
Opt-in for cross-concept cognates after checking? The cognate sets here seem quite big/inclusive.

- *bad/evil*-*belly*-*big*-*child*-*intestines*-*night*-...
- *night*-*old*-*rain*-*red*-...
- *big*-*child*-*small*-*sand*-*spear*-*thunder*-...

**Comment by LinguList** [comment]
@tresoldi, you coded this, and I am quite sure there was no intended cross-semantic cognate coding, can you remember if you checked for global cognate sets?
