### ISSUE TITLE
Error in profile

### ISSUE THREAD

**Issue by tresoldi** [lexibank/bowernpny#15]
We found an error in orthographic profile (git blame says otherwise, but I'm 99% sure it is my fault): `μ` is mapped to `m`, but it should be `ɳ`. Confirmation by the author via Twitter: https://twitter.com/anggarrgoon/status/1496151913284489217 

I can make a PR, but I am not sure if it is the right workflow anymore, especially in terms of regenerating the CLDF.

**Comment by LinguList** [comment]
Yep, please make a PR, thanks!
