### ISSUE TITLE
Zenodo release

### ISSUE THREAD

**Issue by chrzyki** [lexibank/bowernpny#5]
Hiya,

looks like the code/repo is ready for a release but it hasn't been released/pushed to Zenodo yet. Should I go ahead and do that @xrotwang or will you continue working on this repository?

**Comment by LinguList** [comment]
Hi, before releasing, could you please fix the three bipa errors? It would be a shame to have poorly segmented data if we are so close. In the worst case, just use lexemes.tsv. @tresoldi can also have a look...

**Comment by tresoldi** [comment]
I will take care of them.

**Comment by tresoldi** [comment]
Finished with https://github.com/lexibank/bowernpny/commit/947724a7724b806db2cfb5012176f3a516cd9037

As a note, looking at the code (the first dataset I did), there would be a lot to do. If we decide to really review all the datasets setups, this one be my first candidate for rewriting.
